# Generated by Django 2.0.6 on 2019-10-11 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainWikiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('mainImage', models.ImageField(default='', upload_to='WikiApp/')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedWikiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('relatedDescription', models.CharField(max_length=1000)),
                ('relatedImage', models.ImageField(default='', upload_to='WikiApp/')),
            ],
        ),
        migrations.AddField(
            model_name='mainwikimodel',
            name='mainForeignKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WikiApp.RelatedWikiModel'),
        ),
        migrations.AddField(
            model_name='mainwikimodel',
            name='userForeignKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
